### ISSUE TITLE
Return just the secret without any additional logging

### ISSUE THREAD

**Issue by cv711** [hazcod/enpass-cli#102]
Hello!

I'm looking for functionality similar to `secret=$(pass amazon.com)` so the secret can be used in scripts. From what I've seen such functionality doesn't exist or I haven't found it but it would be really useful!

Thanks and keep up the good work!

**Comment by hazcod** [comment]
Hi! I think this would work:

```shell
secret="$(enp -vault=... show amazon.com | grep 'pass :' | cut -c 6-)"
```

**Comment by cv711** [comment]
Sure! But it would be more convenient to get it with a flag straight away.

**Comment by msladek** [comment]
this worked for me under debian:
`enp -vault=... show amazon.com 2>&1 | grep 'pass :' | awk '{ print $NF }'`
the tool writes to stderr instead of stdout.

**Comment by hazcod** [comment]
Fixed in your PR, thanks for the work @msladek !
