### ISSUE TITLE
Distinct exit code for invalid master password

### ISSUE THREAD

**Issue by msladek** [hazcod/enpass-cli#104]
Hey there, firstly thanks a lot for the tool, it is very helpful when working mostly with CLI.

I recently noticed while incorporating `enpasscli` in some bash scripts that all non-successful exits return `1`, e.g. when unable to `copy` because the card wasn't found:
```
$ enp copy asdf || echo "Exit code: $?"
Enter master password: <VALID>
FATA[0004] card not found                               
Exit code: 1
```
However it would be useful to have distinct exit code for providing an invalid master password. Currently it also returns `1`:
```
$ enp copy asdf || echo "Exit code: $?"
Enter master password: <INVALID>
FATA[0001] could not retrieve cards                      error="could not retrieve cards from database: file is not a database"
Exit code: 1
```

Now I'm not at all familiar with golang, but if I'm not mistaken we'd simply need to add e.g. `os.Exit(2)` in the error checks after getting the entries from the vault. I guess that'd be sufficient for my needs at least.

WDYT?

**Comment by hazcod** [comment]
Hi @msladek!
Thanks for reporting this feature. I've added it in https://github.com/hazcod/enpass-cli/commit/0c5760244017a235b57e057c31fb52a430e8dd2f.
It should pop up in a new release in a couple of minutes.

**Comment by msladek** [comment]
Wow that was quick @hazcod!

Quick question: if I provide an invalid master password (with keyfile) I don't get the message `could not open vault`, instead I get the one above `could not retrieve cards`. Will it then still exit with code `1` in my case?

**Comment by hazcod** [comment]
Ohh, my mistake in being too fast.
I can look into this further for you or would appreciate a PR.

**Comment by msladek** [comment]
I guess the problem is a different one now: why doesn't it in my case (pw+keyfile) fail already within `vault.Initialize`? I guess an invalid password should already fail at `vault.openEncryptedDatabase`.

Can you reproduce this issue or have a clue what could be the cause? I'd be happy to provide a PR if I knew how to solve it.

**Comment by hazcod** [comment]
I was thinking the same thing, when looking at https://github.com/hazcod/enpass-cli/blob/master/pkg/enpass/vault.go#L131

**Comment by msladek** [comment]
@hazcod I've found the issue, opened a PR with a solution for this.

**Comment by hazcod** [comment]
@msladek ahh that makes sense, thank you for the work! Closing.
