### ISSUE TITLE
Add option to use primary X selection instead of clipboard

### ISSUE THREAD

**Issue by msladek** [hazcod/enpass-cli#106]
Terminology: https://specifications.freedesktop.org/clipboards-spec/clipboards-latest.txt

It should be possible to control which X selection `enpasscli copy` writes to. By default it always writes to `clipboard` but `primary` may be useful for many scenarios, e.g. paste by middle mouse click or bypass clipboard managers logging entries.

**Comment by hazcod** [comment]
Fixed in https://github.com/hazcod/enpass-cli/commit/ff67a8221fb3370ab1a7ebe09e2f90a4ed02628f , thanks @msladek !

**Comment by msladek** [comment]
@hazcod the release build was successful for linux but failed for darwin https://github.com/hazcod/enpass-cli/runs/4702500913

this is probably because [github.com/atotto/clipboard](https://github.com/atotto/clipboard) has os specific go files and the `Primary` property is available in [clipboard_unix.go](https://github.com/atotto/clipboard/blob/master/clipboard_unix.go) but not in [clipboard_darwin.go](https://github.com/atotto/clipboard/blob/master/clipboard_darwin.go).

thus `clipboard.Primary = true` should only be set on unix, right? I'm not familiar enough with go, how can this be done?

**Comment by hazcod** [comment]
@msladek Hmm, we probably should write a wrapper file with the primary clipboard thing being set in e.g. `clipboard_linux.go` only.

**Comment by msladek** [comment]
If I understand you correctly something along those line:
- extract `clipboard.WriteAll` to a new `clipboard.go` file
- pass `clipboardPrimary` boolean to it, the default `clipboard.go` implementation does nothing with it
- add `clipboard_linux.go` that additionally sets `clipboard.Primary = true`
Does that sound about right?

**Comment by msladek** [comment]
@hazcod see #108 
not sure if we could somehow solve this without a `clipboard_darwin.go` but providing a default implementation, but this should work as well.
