### ISSUE TITLE
No Arguments throws an error v1.4

### ISSUE THREAD

**Issue by nanvenomous** [hazcod/enpass-cli#115]
![no_args_enpass_error](https://user-images.githubusercontent.com/43622197/179334832-efdcaabb-0070-455d-a6a7-7101095d622b.png)
# To reproduce
- download a binary for v1.4.0
- run the command with no arguments
> ./enpasscli

**Comment by msladek** [comment]
Thanks for reporting this issue. I've opened a PR fixing it.
