### ISSUE TITLE
PIN length should be 4 characters

### ISSUE THREAD

**Issue by rdiezsj** [hazcod/enpass-cli#120]
A minimum PIN length of 4 characters is set in the Enpass app itself. cli access should keep the same length

**Comment by msladek** [comment]
The PIN works differently in the GUI app, there the vault is kept open in memory. enpass-cli instead writes the encrypted derived database key to (ram)disk (see #110 for more information). An attacker getting access to this file would find it trivial to brute-force a 4 character PIN.
