### ISSUE TITLE
Pass master password as parameter

### ISSUE THREAD

**Issue by rdiezsj** [hazcod/enpass-cli#121]
A great improvement would be to be able to pass the master password as a parameter to be able to directly unlock the vault

e.g.:

```bash
enpasscli -vault=/xxxxxxxxxxxxx/Vaults/primary -masterpass <PASSWORD> list
```

**Comment by hazcod** [comment]
I'm not sure if we'd want this, since it would mean your master password would be stored in your shell history and viewable in process lists.
Perhaps an environment variable would make more sense?
