### ISSUE TITLE
No support for cloud synced vaults?

### ISSUE THREAD

**Issue by wtflm** [hazcod/enpass-cli#124]
Trying out some basic commands works on a primary, local vault but doing the same on Dropbox or OneDrive connected vaults just gives me
```
ERRO[0002] could not open vault                          error="could not connect to database: file is not a database"
```
Are those really not supported or am I missing something?

**Comment by hazcod** [comment]
@wtflm As a test to see if Dropbox/OneDrive is the cause, can you try copying the database to a local drive and try running enpass-cli on that one?

**Comment by wtflm** [comment]
I created a new local vault in Enpass and copied the .enpassdb and .json files from the Dropbox-synced vault's directory over the newly created ones and get the same error. Additionally, I created yet another local vault, added a dummy entry in it and the same thing...

We're having a rubber duck moment here. I was entering the Enpass master password (as prompted to be fair) for each of the vaults and while it worked for the primary one, not so much for the others. It seems you need to enter the vault's password and with that, all the vaults seem to work as expected. Should the prompt be changed from `Enter master password:` to `Enter vault password:` maybe?

**Comment by hazcod** [comment]
Hi @wtflm , good shout, I've changed this and put this ready for the next release: https://github.com/hazcod/enpass-cli/commit/f086439b19dfda8ba0b61baab04998c4ff4dbabd
