### ISSUE TITLE
.enpass file should not be stored in script path

### ISSUE THREAD

**Issue by erenfro** [hazcod/enpass-cli#14]
in getCards() and CardCompleter(), it's trying to open getScriptPath() + '/.enpass' for write. If pass.py were installed to /usr/bin or /usr/local/bin, this would fail to work because of permissions. 

Instead it should be using either $HOME/.enpass_cli, or even better $XDG_CONFIG_HOME with default to $HOME/.config, appending enpass_cli/config to the result of the former, and of course, automatically creating the directories up as needed.

Reference: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by HazCod** [comment]
Completely valid point, however I do not use this tool anymore personally. All PRs are welcome :-)

**Comment by erenfro** [comment]
I will gladly submit a PR soon! Curious why you don't use this anymore though. Stopped using Enpass?

**Comment by HazCod** [comment]
I like the simplicity of Enpass, but LastPass had tighter integration with my browser and mobile back when I used it. LastPass also did some things I liked in regards to password sharing, instead of just exporting the password like Enpass. The company itself was a factor aswel.

**Comment by crisp2u** [comment]
@HazCod Could you add this info on the README of the project, maybe someone else will take over the development ?

**Comment by HazCod** [comment]
@crisp2u Sure! https://github.com/HazCod/enpass-cli/commit/db3a60d67546a6b7334761760da01c87e8c0f22b

**Comment by hazcod** [comment]
No longer relevant with the Go rewrite, closing.
