### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by seebi** [HazCod/enpass-cli#2]
I've installed enpass-cli but got this error

```
∴ ./pass.py --help
Traceback (most recent call last):
  File "./pass.py", line 4, in <module>
    from pysqlcipher3 import dbapi2 as sqlite
ImportError: No module named 'pysqlcipher3'
```

Do not know how to proceed. Can you help me?

**Comment by HazCod** [comment]
Hi, did you pip install the python dependencies?

E.g. 'python -m pip install -r requirements.txt'

**Comment by seebi** [comment]
yes. exactly as described.

I use pyenv - is this a problem maybe?

**Comment by HazCod** [comment]
Hm, and could you try with python3 instead of python?

**Comment by seebi** [comment]
sure, here the output ...
```
∴ python3 -m pip install -r requirements.txt
Collecting pysqlcipher3 (from -r requirements.txt (line 1))
  Using cached pysqlcipher3-1.0.2.tar.gz
Requirement already satisfied: argcomplete in /Users/seebi/.pyenv/versions/3.5.2/Python.framework/Versions/3.5/lib/python3.5/site-packages (from -r requirements.txt (line 2))
Installing collected packages: pysqlcipher3
  Running setup.py install for pysqlcipher3 ... done
Successfully installed pysqlcipher3
```
after that, I still have this problem
```
∴ ./pass.py
Traceback (most recent call last):
  File "./pass.py", line 4, in <module>
    from pysqlcipher3 import dbapi2 as sqlite
ImportError: No module named 'pysqlcipher3'
```

**Comment by k1b** [comment]
Hi @seebi 
Do you try to run pass.py on Mac OS?

**Comment by seebi** [comment]
Hi @k1b - yes, try to run it under MacOS and via pyenv.

**Comment by k1b** [comment]
@seebi Try to install install sqlcipher via brew:
`brew install sqlcipher`

**Comment by k1b** [comment]
And after this try to install requirements

**Comment by seebi** [comment]
Hi @k1b 
I've installed sqlcipher via bew. now there is a different error message.

```
./pass.py
Traceback (most recent call last):
  File "./pass.py", line 5, in <module>
    from Crypto.Cipher import AES
ImportError: No module named 'Crypto'
```

**Comment by HazCod** [comment]
seebi, try a `pip install pycrypto`

**Comment by seebi** [comment]
@HazCod @k1b - thanks a lot, this solved my issue, can work with it now 👍

**Comment by HazCod** [comment]
Fixed in https://github.com/HazCod/enpass-cli/commit/371d85469ff3f064a55fd801bd3297b37a34b1f7
