### ISSUE TITLE
Alternative Product

### ISSUE THREAD

**Issue by stefanpl** [hazcod/enpass-cli#31]
In the description you mention that you do not use enpass any longer. Did you find something similar which supports CLI interface? It so, would be nice to link it in the description as well. 
Thank you for your efforts!

**Comment by hazcod** [comment]
Hi @stefanpl , I bought the paid version of 1Password for my company.
They have a pretty good security model, security whitepaper and track record.

https://support.1password.com/command-line-getting-started/
