### ISSUE TITLE
Broken cross-compilation

### ISSUE THREAD

**Issue by hazcod** [hazcod/enpass-cli#97]
The release workflow seems to miss some dependencies to be able to cross-compile to e.g. freebsd.

**Comment by Kwbmm** [comment]
Hello!

As stated [here](https://github.com/hazcod/enpass-cli/issues/93#issuecomment-803636931), I managed to craft some binary that are not affected anymore by the `sqlite3` driver missing. I'd be happy to make a PR but I won't be able to produce binaries for all the platforms currently released.

As of now, the only ones that are 100% working are `linux x64`, `linux arm` and (probably) `darwin x64`.

Would doing an initial PR to build for these 3 platform work for you and then we will build up on it and eventually reach working binaries for other platforms (linux 32, win 32/64, freebsd, etc...)?

**Comment by hazcod** [comment]
@Kwbmm thank you so much for your work on this! I'd love a PR!

**Comment by hazcod** [comment]
@Kwbmm I noticed the release pipeline now returns the following: `release failed after 0.08s error=git tag v1.1.2 was not made against commit b2bbba1f491eaae2c1b13edc9298252fbaf4e7c1`

https://github.com/hazcod/enpass-cli/runs/2163531155?check_suite_focus=true

**Comment by Kwbmm** [comment]
Yup, I forgot to create the new tag in the release workflow. Will fix that

**Comment by hazcod** [comment]
1.2.0 is up! https://github.com/hazcod/enpass-cli/releases/tag/v1.2.0
